apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-eventos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-eventos
  template:
    metadata:
      labels:
        app: oracle-eventos
    spec:
      containers:
        - name: oracle-eventos
          image: container-registry.oracle.com/database/express:21.3.0-xe
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_SID
              value: "XE"
            - name: ORACLE_PDB
              value: "XEPDB1"
            - name: ORACLE_PWD
              value: "eventos123"
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
            - name: oracle-scripts
              mountPath: /opt/oracle/scripts/startup
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-eventos-pvc
        - name: oracle-scripts
          configMap:
            name: eventos-init-scripts
